import type { CouncilMember } from './types';

export const studentCouncil: CouncilMember[] = [
  { name: 'Mr. Abdus Samad Khan', title: 'Provost', imageSeed: 'provost' },
  { name: 'Mr. Kazim Ali Shah', title: 'Deputy Provost', imageSeed: 'deputy_provost' },
  { name: 'Mr. Muhammad Shoaib', title: 'Chief Coordinator', imageSeed: 'chief_coordinator' },
  { name: 'Mr. Asim Ali', title: 'Media Secretary', imageSeed: 'media_secretary' },
  { name: 'Ms. Sadeeda Aman', title: 'Finance Secretary', imageSeed: 'finance_secretary' },
  { name: 'Mr. Obaid Ahmad', title: 'President Debating Society', imageSeed: 'debating' },
  { name: 'Mr. Abu Bakr', title: 'President Entrepreneurship Society', imageSeed: 'entrepreneurship' },
  { name: 'Mr. Waqas Ahmed', title: 'President Anti-Drug Abuse Society', imageSeed: 'anti-drug' },
  { name: 'Mr. Salman Khan', title: 'President Sports Society', imageSeed: 'sports' },
  { name: 'Mr. Muhammad Shehryar', title: 'President Blood Donation Society', imageSeed: 'blood_donation' },
  { name: 'Ms. Sahla Tariq', title: 'President Character Building Society', imageSeed: 'character_building' },
  { name: 'Mr. Sameed Ahmad', title: 'President Social Welfare Society', imageSeed: 'social_welfare' },
  { name: 'Mr. Faizan Ali', title: 'President Environmental Society', imageSeed: 'environmental' },
  { name: 'Ms. Amna Shoaib', title: 'President Media Society', imageSeed: 'media' },
  { name: 'Ms. Mehak', title: 'President Women Empowerment Society', imageSeed: 'women_empowerment' },
  { name: 'Mr. Hasnain Yousafzai', title: 'President Dramatic Society', imageSeed: 'dramatic' },
  { name: 'Mr. Sultan', title: 'President Hiking Society', imageSeed: 'hiking' },
  { name: 'Mr. Yasir Sami', title: 'President Legal Circle Society', imageSeed: 'legal_circle' },
  { name: 'Ms. Samreen Usman', title: 'President Think Ink Society', imageSeed: 'think_ink' },
  { name: 'Ms. Rutba Haseen', title: 'President Mental Health Society', imageSeed: 'mental_health' },
  { name: 'Ms. Laiba Khan', title: 'President Peace Building Society', imageSeed: 'peace_building' },
  { name: 'Mr. Nadeem Khan', title: 'President Music Society', imageSeed: 'music' },
  { name: 'Mr. Ajmal Khan', title: 'President Poets of AWKUM Society', imageSeed: 'poets' },
  { name: 'Mr. Ashar Ahmad', title: 'President Technology & Innovation Society', imageSeed: 'tech_innovation' },
  { name: 'Mr. Iftikhar Ali', title: 'President Bits & Bytes Society', imageSeed: 'bits_bytes' },
  { name: 'Mr. Abbas Ahmad', title: 'President Fine-Arts Society', imageSeed: 'fine_arts' },
  { name: 'Mr. Muhammad Zeeshan', title: 'President Prevention of Cruelty Towards Animal Society', imageSeed: 'animal_cruelty' },
  { name: 'Ms. Maria Attique', title: 'President Naat and Qirat Society', imageSeed: 'naat_qirat' },
];
