"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { summarizeFacultyProfile } from "@/ai/flows/summarize-faculty-profiles";
import { Wand2, RefreshCw } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Skeleton } from "../ui/skeleton";

export function SummarizeProfile({ profileText, facultyName }: { profileText: string, facultyName: string }) {
  const [summary, setSummary] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [isOpen, setIsOpen] = useState(false);

  const handleSummarize = async () => {
    setIsLoading(true);
    setError("");
    setSummary("");
    try {
      const result = await summarizeFacultyProfile({ profileText });
      setSummary(result.summary);
    } catch (e) {
      setError("Failed to generate summary. The AI model may be temporarily unavailable. Please try again later.");
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="bg-accent/10 border-accent/50 text-accent-foreground hover:bg-accent/20">
          <Wand2 className="mr-2 h-4 w-4" />
          Summarize with AI
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="text-accent" />
            AI-Powered Summary
          </DialogTitle>
          <DialogDescription>
            A concise overview of {facultyName}'s profile, generated by AI.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4 min-h-[200px] flex flex-col justify-center">
          {!summary && !isLoading && !error && (
            <div className="flex flex-col items-center justify-center gap-4 text-center">
              <p className="text-muted-foreground">Get a quick AI-powered summary of this faculty member's expertise and research interests.</p>
              <Button onClick={handleSummarize} size="lg">
                <Wand2 className="mr-2 h-5 w-5" />
                Generate Summary
              </Button>
            </div>
          )}
          {isLoading && (
            <div className="space-y-3">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-4/5" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-3/5" />
            </div>
          )}
          {error && (
            <Alert variant="destructive">
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          {summary && (
            <div className="space-y-4">
              <p className="text-sm sm:text-base text-foreground/90 whitespace-pre-wrap leading-relaxed">{summary}</p>
            </div>
          )}
        </div>
        <DialogFooter>
          {summary && (
             <Button variant="outline" onClick={handleSummarize} disabled={isLoading}>
                <RefreshCw className={`mr-2 h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
                Regenerate
              </Button>
          )}
          <Button variant="secondary" onClick={() => setIsOpen(false)}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
